### ISSUE TITLE
More native support like RaspberryPi image

### ISSUE THREAD

**Issue by srbala** [AlmaLinux/raspberry-pi#13]
AlmaLinux RaspberryPi image should more native support which are available in standard RaspberryPi. Following are good to have in consideration to native support ...

* [ ] Configure WiFi on first time boot using config `network-data` file from boot partition 
* [ ] Create new using `user-data` config file, create new user on first boot
* [ ] Configure user `SSH` settings based on ssh config entry
* [ ] Expand root partition (running `rootfs-expand` command
* [ ] Make config.txt file updated based on user prompt - screen rescan required etc

Sample config file created by Raspberry Pi imager below 

### Wifi config

```yaml
# File network-config
version: 2
wifis:
  renderer: networkd
  wlan0:
    dhcp4: true
    optional: true
    access-points:
      "MyWiFi-NETWORK_SSID":
# MyWiFi-NETWORK_SSID password hash      
        password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

### User config

```yaml
# File user-data
#cloud-config
hostname: raspberrypi-alma
manage_etc_hosts: true
packages:
- avahi-daemon
apt:
  conf: |
    Acquire {
      Check-Date "false";
    };

users:
- name: piuser
# review group info
  groups: users,wheel,adm,audio,video,cdrom,ftp,games,mail,input,dialout,tape,tty,disk,sys
  shell: /bin/bash
  lock_passwd: false
  passwd: $5$asdffasfasf$sdfsdfdsfsIKOYhIn5tgi9IT4NzaC
  ssh_authorized_keys:
    - ssh-ed25519 AA9txvpeSP8xKAAC3AAAE5XPc6oh39gcjAIKOYhIn5tgi9IT4NzaC1lZDI1NTgOSaXh+ piuser@example.com
  sudo: ALL=(ALL) NOPASSWD:ALL


# check this is needed
runcmd:
- sed -i 's/^s*REGDOMAIN=S*/REGDOMAIN=GB/' /etc/default/crda || true
```
